# Generated by Django 3.0.4 on 2020-04-25 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарий', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Публикацыя', 'verbose_name_plural': 'Публикацыи'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='autor_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Автор кометария'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=80, verbose_name='Название публткацыи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=300, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_name',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pub_text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
