# Generated by Django 3.0.4 on 2020-04-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorders',
            options={'verbose_name': 'Заказ на продажу', 'verbose_name_plural': 'Заказы на продажу'},
        ),
    ]
